In [5]:
import numpy as np
#create matrices
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#Addition
C=A+B
#Substraction
D=A-B
#Multiplication(element-wise)
E=A*B
#Matrix multiplication
F=np.dot(A,B)# or A@B
#Transpose
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubstraction:")
print(D)
print("\n/Element-wise Multiplication:")
print(E)
print("\n/Matrix Multiplication:")
print(F)
print("\nTranspose;")
print(A_transpose)

Addition:
[[ 6  8]
 [10 12]]

Substraction:
[[-4 -4]
 [-4 -4]]

/Element-wise Multiplication:
[[ 5 12]
 [21 32]]

/Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose;
[[1 3]
 [2 4]]
